version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: whispers-postgres
    environment:
      POSTGRES_DB: whispers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - whispers_pg_data:/var/lib/postgresql/data

volumes:
  whispers_pg_data:
